/* Inlines src/styles.css, src/data.js and src/app.js into a single
   self-contained index.html that runs from a double-click on file://.
   Usage: node build.js */
const fs = require('fs');
const path = require('path');

const root = __dirname;
const read = p => fs.readFileSync(path.join(root, p), 'utf8');

const shell = read('src/shell.html');
const css = read('src/styles.css');
const data = read('src/data.js');
const app = read('src/app.js');

const banner = `<!--
  Ha Koo Soong Wai — Senior-to-Senior Health Network
  Generated by build.js from src/. Edit the files in src/, then run: node build.js
-->`;

const out = shell
  .replace('<!--CSS-->', `<style>\n${css}\n</style>`)
  .replace('<!--JS-->', `<script>\n${data}\n\n${app}\n</script>`)
  .replace('<!doctype html>', `<!doctype html>\n${banner}`);

fs.writeFileSync(path.join(root, 'index.html'), out);

/* A second copy for publishing as a hosted page: same content, minus the
   document wrapper the host supplies. Keeps one source of truth. */
const artifact = out
  .replace(/<!doctype html>\s*/i, '')
  .replace(banner, '')
  .replace(/<\/?html[^>]*>\s*/gi, '')
  .replace(/<\/?head>\s*/gi, '')
  .replace(/<\/?body>\s*/gi, '')
  .trim();

fs.writeFileSync(path.join(root, 'artifact.html'), artifact);

const kb = n => (Buffer.byteLength(n) / 1024).toFixed(1);
console.log(`index.html written — ${kb(out)} KB  (double-click to open)`);
console.log(`artifact.html written — ${kb(artifact)} KB  (hosted page)`);
