/* ==========================================================================
   Seed content. Everything the prototype renders comes from here, so the
   curriculum, the seniors and the escalation rules are all editable in one
   place without touching app logic.
   ========================================================================== */

const DATA = {

  /* ---- the signed-in mentor ------------------------------------------- */
  mentor: {
    id: 'somsri',
    name: 'Mrs. Somsri',
    surname: 'Thongchai',
    age: 68,
    gender: 'female',
    district: 'Bang Kapi, Bangkok',
    initials: 'ST',
    av: 'av--g1',
    since: 'March 2026',
    languages: 'Thai, Lao',
    former: 'Retired primary school teacher',
    emergency: 'Nalinee (daughter) · 081 234 5678',
    mentorId: 'SW-2026-0418',
    available: ['Mon', 'Tue', 'Thu', 'Sat'],
  },

  nurse: {
    name: 'Nurse Anong',
    surname: 'Rojana',
    role: 'Community health nurse',
    site: 'Bang Kapi Community Health Centre',
    initials: 'AR',
    av: 'av--g2',
    mentorsSupervised: 24,
  },

  /* ---- the academy ----------------------------------------------------- */
  courses: [
    {
      id: 'vitals',
      title: 'Checking blood pressure and pulse',
      by: 'Nurse Anong Rojana',
      org: 'Bang Kapi Community Health Centre',
      cover: 'cv-1',
      icon: 'pulse',
      minutes: 12,
      recommended: true,
      outcome: 'Take a reliable blood pressure reading at a neighbour\'s home and know when the number needs a nurse.',
      lessons: [
        {
          t: 'Why blood pressure matters',
          m: 4,
          body: [
            'Blood pressure is the push of blood against the walls of your arteries. It is written as two numbers. The top number (systolic) is the push when the heart squeezes. The bottom number (diastolic) is the push when the heart rests between beats.',
            'A normal reading for an older adult is around <strong>120/80</strong>. Many older people live comfortably at <strong>130–140/80</strong>, especially if they take medication for it.',
            'The difficult part is that high blood pressure usually has <strong>no symptoms at all</strong>. A person can feel perfectly well and still be at risk of a stroke. This is why we measure it instead of waiting for someone to complain.',
            'That is the whole reason a trained neighbour is useful. You are not diagnosing anything. You are taking a number that would otherwise not be taken until the next clinic visit, months away.',
          ],
          key: 'High blood pressure is silent. Measuring it is the only way to know.',
        },
        {
          t: 'How to take a reading properly',
          m: 5,
          body: [
            'A reading is only useful if it was taken the same way every time. Six things decide the result:',
            '<strong>1. Rest first.</strong> The person sits quietly for five minutes before the cuff goes on. Walking to answer the door can raise the number by 10–15 points.',
            '<strong>2. Sit properly.</strong> Back supported, both feet flat on the floor, legs uncrossed.',
            '<strong>3. Arm at heart level.</strong> Rest the forearm on a table. If the arm hangs down, the reading comes out too high.',
            '<strong>4. Bare arm.</strong> A sleeve rolled up tightly acts like a tourniquet. Ask them to take the arm out of the sleeve.',
            '<strong>5. No talking.</strong> Talking during the measurement adds points.',
            '<strong>6. Two readings, one minute apart.</strong> Write down both. The second is usually the truer one.',
          ],
          key: 'Same position, same arm, same rest period, every visit. Consistency is what makes the trend meaningful.',
          warn: 'Avoid measuring within 30 minutes of coffee, tea, cigarettes or exercise. Wait if the person has just climbed stairs.',
        },
        {
          t: 'When to raise a flag',
          m: 3,
          body: [
            'Most readings you take will be ordinary. Write them down and move on. A few will need action.',
            '<strong>Repeat first.</strong> If the first reading is high, let the person rest five more minutes and measure again. One high reading is often just the walk over.',
            'If the second reading is still high, or the person has symptoms, that is a flag. Send it to the nurse with your note. You are not expected to decide what it means — that is her job.',
          ],
          key: 'You report. The nurse decides. That division is what keeps everyone safe.',
          crit: 'If the reading is 180/120 or above, or the person has chest pain, sudden weakness on one side, slurred speech or blurred vision — call emergency services first, then tell the nurse.',
          levels: [
            { range: 'Below 120/80', label: 'Normal', tone: 'good' },
            { range: '120–139 / 80–89', label: 'Watch at next visit', tone: 'good' },
            { range: '140–159 / 90–99', label: 'Flag to nurse', tone: 'warn' },
            { range: '160/100 or above', label: 'Flag today', tone: 'crit' },
            { range: 'Below 90/60 with dizziness', label: 'Flag today', tone: 'crit' },
          ],
        },
      ],
      quiz: [
        {
          q: 'Mr. Prasert\'s first reading is 152/94. What do you do next?',
          options: [
            'Send it to the nurse straight away',
            'Let him rest five minutes and measure again',
            'Ask him to take an extra blood pressure tablet',
            'Come back next week and measure again',
          ],
          a: 1,
          why: 'One high reading is often caused by the walk over. Always rest five minutes and repeat before flagging. And never advise on medication — that is the nurse\'s decision.',
        },
        {
          q: 'Which of these raises a blood pressure reading that would otherwise be normal?',
          options: [
            'Resting for five minutes first',
            'The arm resting on a table at heart level',
            'The arm hanging down by the side of the chair',
            'Both feet flat on the floor',
          ],
          a: 2,
          why: 'An arm below heart level reads too high. Support the forearm on a table so the cuff sits level with the heart.',
        },
        {
          q: 'Auntie Malee reads 186/122 and says she has a bad headache and blurred vision. What comes first?',
          options: [
            'Call emergency services, then tell the nurse',
            'Take a third reading to be sure',
            'Help her lie down and check again tomorrow',
            'Send the number to the nurse through the app',
          ],
          a: 0,
          why: 'At 180/120 and above with symptoms, this is a possible hypertensive emergency. Emergency services come first. The nurse is told immediately after.',
        },
      ],
    },

    {
      id: 'falls',
      title: 'Spotting fall risk at home',
      by: 'Physiotherapist Kittipong Suwan',
      org: 'Bang Kapi Community Health Centre',
      cover: 'cv-2',
      icon: 'walk',
      minutes: 15,
      outcome: 'Walk through a neighbour\'s home and find the six hazards that cause most falls, then fix them together.',
      lessons: [
        {
          t: 'Why a fall changes everything',
          m: 5,
          body: [
            'For a person of 75, a broken hip is not a simple injury. Roughly one in three older adults who break a hip never return to walking the way they did before.',
            'There is a second harm that is quieter. After a fall, people become afraid of falling. They walk less, go out less, and lose strength — which makes the next fall more likely. The fear does as much damage as the fracture.',
            'The good news is that most falls at home are caused by a small number of things that are easy to fix. A rug. A cable. A light switch that is too far from the bed.',
            'Your job is not to make the home perfect. It is to find the two or three hazards that matter most for this particular person and fix those.',
          ],
          key: 'Fear of falling causes as much lost mobility as the fall itself.',
        },
        {
          t: 'The five-minute safety scan',
          m: 6,
          body: [
            'Walk the route the person actually walks: bed to toilet, bed to kitchen, front door to gate. Stop at each of these:',
            '<strong>Loose rugs and mats.</strong> The single most common cause. Either remove them or fix them down with double-sided tape.',
            '<strong>Cables across a walking path.</strong> Run them along a wall or behind furniture.',
            '<strong>The night path.</strong> Can they reach a light without getting out of bed? A plug-in night light costs very little and prevents the most dangerous walk of the day.',
            '<strong>Bathroom.</strong> Wet floor, no grab bar by the toilet, a step into the shower. A suction grab bar and a non-slip mat are the two cheapest wins available.',
            '<strong>Footwear.</strong> Socks alone on a tiled floor are slippery. Loose slippers catch. Firm-fitting shoes with a back are safest.',
            '<strong>Clutter on the floor.</strong> Newspapers, shoes, extension cords, pet bowls.',
          ],
          key: 'Almost every serious fall happens on a route the person walks every single day.',
          warn: 'Do not move furniture around without asking. A person who has lived in a home for thirty years knows where things are in the dark. Changing that can make things worse.',
        },
        {
          t: 'Walking aids and getting up safely',
          m: 4,
          body: [
            'A walking stick or frame that is the wrong height causes more problems than it solves. Standing straight, the handle of a stick should reach the crease of the wrist.',
            'Teach the person what to do if they do fall. Many older people lie on the floor for hours because they do not know how to get up and are afraid to try.',
            '<strong>The safe way up:</strong> roll onto the side, bring the knees up, push up onto hands and knees, crawl to a stable chair, put both hands on the seat, and push up while keeping one knee on the floor. Practise it once while they are well.',
            'If they are injured, in pain, or cannot get up — do not force it. Call for help, keep them warm, and stay with them.',
          ],
          key: 'Practise getting up from the floor before it is ever needed.',
        },
      ],
      quiz: [
        {
          q: 'Which single change prevents the most falls at home?',
          options: [
            'Removing or taping down loose rugs',
            'Replacing all the furniture',
            'Asking the person to walk more slowly',
            'Keeping the person indoors after dark',
          ],
          a: 0,
          why: 'Loose rugs and mats are the most common cause of falls at home, and fixing them costs almost nothing.',
        },
        {
          q: 'Standing straight, where should the handle of a walking stick reach?',
          options: [
            'The top of the shoulder',
            'The crease of the wrist',
            'The middle of the thigh',
            'The hip bone',
          ],
          a: 1,
          why: 'The crease of the wrist is the standard height. A stick that is too low makes the person stoop; too high and they cannot take weight through it.',
        },
        {
          q: 'You notice a loose rug on the path between Auntie Malee\'s bed and the toilet. What is the best approach?',
          options: [
            'Remove it without mentioning it',
            'Tell her it must go, and explain why',
            'Fix it down together and explain the risk',
            'Report it to the nurse and let her deal with it',
          ],
          a: 2,
          why: 'Fixing it together keeps her in control of her own home and teaches her the reason, so she can spot the next hazard herself.',
        },
      ],
    },

    {
      id: 'mind',
      title: 'Everyday mental wellbeing for seniors',
      by: 'Dr. Pimchanok Saelim',
      org: 'Bang Kapi Community Health Centre',
      cover: 'cv-3',
      icon: 'heart',
      minutes: 10,
      outcome: 'Notice when a neighbour is withdrawing, start a conversation that helps, and know when it is more than sadness.',
      lessons: [
        {
          t: 'Loneliness is a health condition',
          m: 3,
          body: [
            'Persistent loneliness carries a health risk comparable to smoking, and a higher risk of heart disease and dementia. It is not a mood. It changes the body.',
            'Retirement, the loss of a spouse, and grown children moving away all remove the daily contact a person used to get without trying. For many older people, a visit from you is the only conversation of the day.',
            'This is the part of the network that a clinic cannot provide. A nurse can check blood pressure in ten minutes. She cannot drop by on Tuesday for tea.',
          ],
          key: 'Regular, ordinary contact is treatment, not just company.',
        },
        {
          t: 'How to listen so someone opens up',
          m: 4,
          body: [
            'Most of us respond to a problem by trying to fix it. When someone says they feel useless, we say "don\'t be silly, you\'re wonderful". It comes from kindness, but it closes the conversation.',
            'Try instead:',
            '<strong>Ask an open question.</strong> "How have the mornings been lately?" rather than "Are you okay?"',
            '<strong>Stay quiet for a moment.</strong> Silence gives permission to say the real thing.',
            '<strong>Reflect it back.</strong> "So the days feel long since Somchai passed." That one sentence tells them you heard it.',
            '<strong>Do not rush to reassurance.</strong> Let them finish before you offer anything.',
            'Then come back. The second visit matters more than the first, because that is when they learn you meant it.',
          ],
          key: 'Reflect what you heard before you offer anything. Being heard is the intervention.',
        },
        {
          t: 'When it is more than sadness',
          m: 3,
          body: [
            'Sadness passes with company. Depression and early dementia do not, and both are treatable when they are caught. Hand these to the nurse — do not try to manage them yourself.',
            'Things worth flagging:',
            '<strong>Two weeks or more</strong> of low mood, or losing interest in things they always enjoyed.',
            '<strong>Not eating</strong>, or losing weight without trying.',
            '<strong>Stopping their own medication</strong>, or saying things like "what is the point".',
            '<strong>Memory that interferes with daily life</strong> — missing medication repeatedly, getting lost on a familiar route, repeating the same question within minutes.',
            'If someone mentions wanting to die, do not leave it. Stay with them, tell the nurse the same day, and do not promise to keep it secret.',
          ],
          key: 'Two weeks of low mood, or memory loss that interferes with daily life, goes to the nurse.',
          crit: 'If someone talks about ending their life, stay with them and contact the nurse or emergency services the same day. Never agree to keep it a secret.',
        },
      ],
      quiz: [
        {
          q: 'Uncle Somchai says the days feel empty since his wife died. What is the most helpful response?',
          options: [
            '"You shouldn\'t think like that — you have your grandchildren."',
            '"So the days feel long since she passed."',
            '"You should join the community centre activities."',
            '"Everyone feels that way at first."',
          ],
          a: 1,
          why: 'Reflecting back what you heard shows you understood, and it lets him keep talking. Reassurance and advice both close the conversation.',
        },
        {
          q: 'Which of these should be handed to the nurse rather than managed by you?',
          options: [
            'A neighbour who is quiet for a few days after a funeral',
            'A neighbour who says he does not want to join the walking group',
            'Two weeks of low mood and losing interest in everything',
            'A neighbour who misses his friends who moved away',
          ],
          a: 2,
          why: 'Low mood lasting two weeks or more, with loss of interest, is a sign of depression — treatable, and the nurse\'s to assess.',
        },
        {
          q: 'A neighbour tells you she sometimes thinks about ending her life, and asks you not to tell anyone. What do you do?',
          options: [
            'Keep the secret — she trusted you',
            'Stay with her and contact the nurse the same day',
            'Wait to see whether she brings it up again',
            'Tell another neighbour so they can check on her',
          ],
          a: 1,
          why: 'Never keep this secret. Stay with her and reach the nurse or emergency services today. Safety comes before the promise.',
        },
      ],
    },

    {
      id: 'move',
      title: 'Leading a safe walking group',
      by: 'Physiotherapist Kittipong Suwan',
      org: 'Bang Kapi Community Health Centre',
      cover: 'cv-4',
      icon: 'users',
      minutes: 11,
      outcome: 'Run a weekly walking group for older adults without anyone coming to harm.',
      lessons: [
        {
          t: 'Who can join, and who needs a doctor first',
          m: 3,
          body: [
            'Most older adults can walk with a group. A few need a doctor\'s clearance before they start, and it is your job to ask rather than assume.',
            'Ask everyone to check with a doctor first if they have: chest pain on effort, a recent heart attack or stroke within three months, dizziness or blackouts, or a fall in the last month.',
            'Everyone else can start at an easy pace and build up. Walking is one of the safest things an older person can do — the risk is not the walking, it is the pace and the ground.',
          ],
          key: 'Ask about the four conditions every time someone new joins.',
        },
        {
          t: 'Warm-up, pace and the talk test',
          m: 4,
          body: [
            '<strong>Warm up for five minutes.</strong> March on the spot, roll the shoulders, circle the ankles, gentle knee lifts. Cold muscles and cold morning air are a bad combination.',
            '<strong>Set the pace with the talk test.</strong> Everyone should be able to hold a conversation while walking. If someone can only manage one or two words between breaths, the group is going too fast.',
            '<strong>Build up slowly.</strong> Start with 15 minutes and add five minutes a week until you reach 30. Three sessions a week is enough.',
            '<strong>Cool down and stretch.</strong> Slow the last few minutes, then stretch the calves and the backs of the thighs.',
          ],
          key: 'If they cannot talk, they are walking too fast.',
        },
        {
          t: 'Running the session',
          m: 4,
          body: [
            '<strong>Walk the route yourself first.</strong> Check for uneven paving, steps without a handrail, and anywhere without shade.',
            '<strong>Count heads at the start.</strong> Write the number down. Count again at the halfway point and at the end.',
            '<strong>Put someone at the back.</strong> The sweep stays behind the slowest walker. Nobody is ever left alone at the back.',
            '<strong>Carry water and a phone.</strong> Older adults feel thirst later, so offer water at the halfway stop rather than waiting to be asked.',
            '<strong>Have a plan for a fall.</strong> Know the nearest clinic, and know who in the group has a phone and can call.',
            '<strong>Stop the session</strong> if anyone has chest pain, severe breathlessness, dizziness or a sudden headache. Sit them down, do not let them walk it off, and call for help.',
          ],
          key: 'Count heads at the start, at halfway, and at the end. Every session.',
          warn: 'In hot weather, walk before 8am and shorten the route. Older adults overheat faster and feel it later.',
        },
      ],
      quiz: [
        {
          q: 'How do you know the group is walking at the right pace?',
          options: [
            'Everyone is sweating by the end',
            'Everyone can hold a conversation while walking',
            'Everyone keeps up with the leader',
            'The group finishes within the hour',
          ],
          a: 1,
          why: 'The talk test is the standard guide. Being unable to talk means the pace is too hard for that person.',
        },
        {
          q: 'Which person needs a doctor\'s clearance before joining the group?',
          options: [
            'Auntie Malee, 72, whose knees ache in the morning',
            'Uncle Boonmee, 81, who had a fall last month',
            'Mr. Prasert, 74, who takes blood pressure medication',
            'Auntie Wilai, 68, who retired recently and walks daily',
          ],
          a: 1,
          why: 'A fall within the last month is one of the four conditions that need a doctor\'s clearance before starting.',
        },
        {
          q: 'What is the sweep\'s job?',
          options: [
            'To lead the group and set the pace',
            'To stay behind the slowest walker so nobody is alone',
            'To carry the first aid kit at the front',
            'To count heads at the end',
          ],
          a: 1,
          why: 'The sweep walks behind the last person. Nobody is ever left at the back on their own.',
        },
      ],
    },

    {
      id: 'meds',
      title: 'Medication reminders and eating well',
      by: 'Pharmacist Wipada Chaiyo',
      org: 'Bang Kapi Community Health Centre',
      cover: 'cv-5',
      icon: 'pill',
      minutes: 13,
      outcome: 'Help a neighbour take their medication on time and eat properly, without ever advising on the medicine itself.',
      lessons: [
        {
          t: 'Help, but never prescribe',
          m: 4,
          body: [
            'This is the most important rule in the whole academy, so it comes first.',
            '<strong>You never advise anyone to change a dose, stop a medicine, or take someone else\'s.</strong> Not even if the pills look the same. Not even if they say the doctor told them something different. You pass it to the nurse or the pharmacist.',
            'What you can do is everything around the medicine: remembering, organising, timing, and noticing.',
            'If someone says a medicine makes them feel unwell, write down exactly what they said and which medicine, and send it to the nurse. That observation is genuinely valuable and often missed.',
          ],
          key: 'You manage the routine. The nurse and pharmacist manage the medicine.',
          crit: 'Never advise on a dose, never share medicine between people, and never tell someone to stop taking something.',
        },
        {
          t: 'Building a routine that survives',
          m: 5,
          body: [
            'Forgetting medication is rarely about memory. It is about the routine being fragile. Three things make it hold:',
            '<strong>One place.</strong> All the medication lives in one spot, and it is not the kitchen counter where things get moved.',
            '<strong>One time, tied to a habit.</strong> "After breakfast" works. "Twice a day" does not. Anchor each dose to something they already do without thinking.',
            '<strong>A weekly pill organiser.</strong> Filling it together on a Sunday takes five minutes and shows at a glance whether a day was missed.',
            'Also check what else they take. Herbal remedies, vitamins and painkillers bought at the market all count, and the nurse needs to know about them.',
          ],
          key: 'Anchor each dose to something the person already does without thinking.',
        },
        {
          t: 'Eating well when cooking for one',
          m: 4,
          body: [
            'Cooking for one is discouraging, and appetite drops with age. Two things matter more than anything else:',
            '<strong>Protein at every meal.</strong> Eggs, fish, chicken, beans, tofu, milk. Without it, muscle is lost, and muscle is what keeps a person walking and catching themselves when they stumble.',
            '<strong>Water, offered rather than waited for.</strong> Older adults feel thirst later and are often mildly dehydrated without knowing. Offer a glass at every visit. Keep a filled bottle where they sit.',
            'Practical helps: cook once and freeze in portions; keep easy protein in the house (eggs, tinned fish, tofu); eat the main meal at midday when appetite is best.',
            'Watch for weight loss without trying. That is a flag for the nurse, not something to fix with encouragement.',
          ],
          key: 'Protein at every meal, and water offered rather than waited for.',
          warn: 'Losing weight without trying, or a sudden dislike of food, goes to the nurse.',
        },
      ],
      quiz: [
        {
          q: 'Mr. Prasert says his blood pressure tablets make him dizzy, and asks if he should take half. What do you do?',
          options: [
            'Suggest half a tablet and tell the nurse at the next visit',
            'Tell him to stop taking them until he sees the doctor',
            'Write down what he said and send it to the nurse today',
            'Give him the number for the pharmacy and let him ring',
          ],
          a: 2,
          why: 'You never advise on a dose. Recording exactly what he said and getting it to the nurse the same day is the correct action — and that observation is genuinely useful.',
        },
        {
          q: 'Which instruction is a workable medication routine?',
          options: [
            '"Take one tablet twice a day"',
            '"Take one tablet after breakfast and one after dinner"',
            '"Take one tablet every 12 hours"',
            '"Take as needed for blood pressure"',
          ],
          a: 1,
          why: 'Anchoring each dose to something the person already does without thinking is what makes a routine hold.',
        },
        {
          q: 'Which of these is worth flagging to the nurse?',
          options: [
            'Auntie Wilai has started eating her main meal at midday',
            'Mr. Boonmee has lost weight without trying',
            'Uncle Somchai keeps a bottle of water by his chair',
            'Auntie Malee filled her pill organiser on Sunday',
          ],
          a: 1,
          why: 'Weight loss without trying is a clinical sign, not something to solve with encouragement.',
        },
      ],
    },
  ],

  /* ---- the seniors in and around the mentor's circle -------------------- */
  seniors: [
    {
      id: 'prasert',
      name: 'Mr. Prasert',
      age: 74,
      initials: 'PP',
      av: 'av--g2',
      area: 'Bang Kapi · 600 m away',
      distance: 0.6,
      livesAlone: true,
      conditions: ['High blood pressure', 'Type 2 diabetes'],
      needs: ['Blood pressure check', 'Medication reminders', 'Company'],
      since: 'April 2026',
      nextDue: 'Today',
      notes: 'Lives alone since his wife moved to their daughter\'s in Chiang Mai. Takes three tablets in the morning. Walks with a stick since a knee replacement two years ago.',
      interest: 96,
      inCircle: true,
      history: [
        { d: '2 Sep', sys: 138, dia: 86, pulse: 74, tone: 'good', note: 'All well. Walked to the market with his neighbour.' },
        { d: '26 Aug', sys: 146, dia: 90, pulse: 78, tone: 'warn', note: 'Slightly high. Had walked over in the heat.' },
        { d: '19 Aug', sys: 134, dia: 82, pulse: 72, tone: 'good', note: 'Tablets organised for the week.' },
      ],
    },
    {
      id: 'malee',
      name: 'Auntie Malee',
      age: 72,
      initials: 'ML',
      av: 'av--g3',
      area: 'Bang Kapi · 1.8 km away',
      distance: 1.8,
      livesAlone: false,
      conditions: ['Arthritis'],
      needs: ['Walking companion', 'Grocery help', 'Conversation'],
      since: 'February 2026',
      nextDue: 'In 3 days',
      notes: 'Lives with her son, who works long shifts. Keen gardener, but her knees have made the garden difficult this year. Very sociable — she is the one who will notice if someone else has gone quiet.',
      interest: 94,
      inCircle: true,
      history: [
        { d: '5 Sep', sys: 128, dia: 78, pulse: 70, tone: 'good', note: 'Good spirits. Joined the walking group twice.' },
        { d: '29 Aug', sys: 126, dia: 80, pulse: 72, tone: 'good', note: 'Knees sore after gardening.' },
      ],
    },
    {
      id: 'somchai',
      name: 'Uncle Somchai',
      age: 79,
      initials: 'SC',
      av: 'av--g4',
      area: 'Bang Kapi · 900 m away',
      distance: 0.9,
      livesAlone: true,
      conditions: ['Recent fall', 'Osteoarthritis'],
      needs: ['Post-fall check-ins', 'Home safety help', 'Company'],
      since: 'Not yet in your circle',
      nextDue: 'Needs a first visit',
      notes: 'Fell in his bathroom six weeks ago. No fracture, but he has stopped going out alone since. His daughter rings every evening. He needs a doctor\'s clearance before joining the walking group.',
      interest: 91,
      inCircle: false,
      history: [],
    },
    {
      id: 'wilai',
      name: 'Auntie Wilai',
      age: 68,
      initials: 'WL',
      av: 'av--g5',
      area: 'Bang Kapi · 1.2 km away',
      distance: 1.2,
      livesAlone: false,
      conditions: ['None recorded'],
      needs: ['Newly retired', 'Social connection'],
      since: 'Not yet in your circle',
      nextDue: 'Needs a first visit',
      notes: 'Retired from the bank four months ago. Fit and capable, but says the weeks feel shapeless. A strong candidate to train as a mentor herself once she finds her feet.',
      interest: 88,
      inCircle: false,
      history: [],
    },
    {
      id: 'boonmee',
      name: 'Mr. Boonmee',
      age: 81,
      initials: 'BM',
      av: 'av--g6',
      area: 'Bang Kapi · 2.1 km away',
      distance: 2.1,
      livesAlone: false,
      conditions: ['Mild heart failure', 'Hearing loss'],
      needs: ['Wellbeing check-ins', 'Medication routine'],
      since: 'June 2026',
      nextDue: 'In 5 days',
      notes: 'Lives with his daughter. She works daytime, so he is alone from 8am to 6pm. Hard of hearing — speak facing him and slightly lower, not louder. Weighs himself daily; a sudden gain goes to the nurse.',
      interest: 85,
      inCircle: true,
      history: [
        { d: '31 Aug', sys: 132, dia: 84, pulse: 76, tone: 'good', note: 'Weight steady. Daughter filled the organiser.' },
      ],
    },
  ],

  /* ---- group activities ------------------------------------------------- */
  activities: [
    {
      id: 'walk',
      title: 'Morning walking group',
      place: 'Klong Saen Saep park, Gate 2',
      day: 'Tuesday & Thursday',
      time: '6:30 – 7:30',
      kind: 'Exercise',
      icon: 'walk',
      lead: 'You',
      joined: false,
      capacity: 12,
      attendees: ['malee', 'wilai', 'boonmee', 'prasert'],
      note: 'Flat paved loop, 1.4 km. Benches every 300 m. Sweep walks at the back.',
    },
    {
      id: 'chair',
      title: 'Chair exercise for stiff joints',
      place: 'Bang Kapi community centre, Room 2',
      day: 'Monday & Wednesday',
      time: '9:00 – 10:00',
      kind: 'Exercise',
      icon: 'users',
      lead: 'Khun Ratsami',
      joined: true,
      capacity: 15,
      attendees: ['boonmee', 'somchai', 'malee'],
      note: 'Seated mobility and balance work. Suitable for anyone who cannot stand for long.',
    },
    {
      id: 'garden',
      title: 'Community garden morning',
      place: 'Soi 42 allotments',
      day: 'Wednesday',
      time: '7:00 – 9:00',
      kind: 'Social',
      icon: 'leaf',
      lead: 'Uncle Chai',
      joined: false,
      capacity: 10,
      attendees: ['malee', 'wilai'],
      note: 'Raised beds so nobody has to kneel. Bring a hat and water.',
    },
    {
      id: 'cook',
      title: 'Cooking for one, together',
      place: 'Bang Kapi community centre kitchen',
      day: 'Saturday',
      time: '10:00 – 12:00',
      kind: 'Learning',
      icon: 'pot',
      lead: 'Pharmacist Wipada',
      joined: false,
      capacity: 12,
      attendees: ['wilai', 'prasert', 'boonmee'],
      note: 'Simple high-protein meals that freeze well. Everyone takes home two portions.',
    },
  ],

  /* ---- pre-existing flags in the nurse's inbox -------------------------- */
  cases: [
    {
      id: 'c-1041',
      seniorId: 'boonmee',
      mentor: 'Uncle Chai, 71',
      raised: '2 hours ago',
      severity: 'warn',
      reason: 'Weight up 2.1 kg in three days',
      detail: 'Mr. Boonmee reported no new symptoms. He says his rings feel tight. Daughter is away until Friday.',
      vitals: { sys: 132, dia: 84, pulse: 76 },
      status: 'open',
      action: null,
    },
    {
      id: 'c-1038',
      seniorId: 'wilai',
      mentor: 'Auntie Malee, 72',
      raised: 'Yesterday',
      severity: 'warn',
      reason: 'Low mood noted on two consecutive visits',
      detail: 'Auntie Malee sat with her for an hour. Wilai says she is sleeping badly since retiring and feels she has nothing to do. No mention of self-harm.',
      vitals: { sys: 124, dia: 78, pulse: 72 },
      status: 'open',
      action: null,
    },
  ],

  /* ---- district roll-up for the system panel --------------------------- */
  district: {
    name: 'Bang Kapi district',
    mentors: 318,
    mentorsTrained: 412,
    checkins: 6840,
    flags: 512,
    profHours: 1284,
  },

  /* ---- narration shown beside the app, per route ----------------------- */
  notes: {
    home: {
      k: 'Step 1 · The capable senior',
      v: 'A healthy older adult signs up. She is not a patient here — she is the beginning of the workforce.',
    },
    train: {
      k: 'Step 2 · Trained by professionals',
      v: 'Every course is written and signed off by a named clinician at the community health centre. The academy is what turns willingness into something a health system can rely on.',
    },
    lesson: {
      k: 'Step 2 · Trained by professionals',
      v: 'The content is deliberately narrow and practical. A mentor is taught to observe and report — never to diagnose or adjust medication.',
    },
    quiz: {
      k: 'Step 2 · Trained by professionals',
      v: 'Assessment is what makes the certification worth something. A mentor who cannot tell a high reading from an emergency is a risk, not a resource.',
    },
    certificate: {
      k: 'Step 3 · Certified mentor',
      v: 'Certification is issued against the clinic\'s standard, so the nurse knows exactly what this person has been trained to do.',
    },
    circle: {
      k: 'Step 4 · Supporting the community',
      v: 'Matching happens by distance and by need. Most of what is delivered here is company and consistency, not clinical care — and that is the point.',
    },
    senior: {
      k: 'Step 4 · Supporting the community',
      v: 'The mentor holds a light record: observations over time. A trend is what a single clinic visit cannot see.',
    },
    checkin: {
      k: 'Step 4 · Supporting the community',
      v: 'A structured check-in turns a friendly visit into usable data — and the structure is what makes it safe to delegate.',
    },
    result: {
      k: 'Step 4 · Supporting the community',
      v: 'The app applies the clinic\'s own thresholds. The mentor does not judge severity; the rules do.',
    },
    triage: {
      k: 'Step 5 · Pressure comes off the system',
      v: 'This is the whole argument in one screen. A neighbour noticed something a clinic would have seen months later, and the nurse acts on it in minutes without leaving her desk.',
    },
    activity: {
      k: 'Step 4 · Supporting the community',
      v: 'Group activity is the cheapest health intervention in the model. It reaches people who would never book an appointment.',
    },
    session: {
      k: 'Step 4 · Supporting the community',
      v: 'Attendance and headcounts are logged like any other clinical record, because a walking group with no sweep is a safeguarding risk.',
    },
    impact: {
      k: 'Step 5 · Pressure comes off the system',
      v: 'Both halves of the ledger matter: the health that was protected, and the professional hours that were never needed.',
    },
    profile: {
      k: 'Step 3 · Certified mentor',
      v: 'The profile is a credential, not a social page. It is what lets a health system put a trained volunteer in front of a frail adult.',
    },
    nurse: {
      k: 'The professional\'s view',
      v: 'This is what the nurse sees instead of a queue of unreachable patients: a supervised network of trained eyes, with the serious cases surfaced to the top.',
    },
    case: {
      k: 'The professional\'s view',
      v: 'The nurse keeps clinical authority. The mentor widens her reach without diluting her judgement.',
    },
    mentors: {
      k: 'The professional\'s view',
      v: 'Twenty-four trained seniors reporting into one nurse. That ratio is the entire economic case for the network.',
    },
  },
};
